#!/bin/sh
# Worker entrypoint: prepare the persistent volume, then run openwork-server
# with a managed OpenCode engine. Tokens are read from OPENWORK_TOKEN and
# OPENWORK_HOST_TOKEN (generated by the Railway template); if absent,
# openwork-server generates them and logs the host token once.
set -eu

PORT_TO_USE="${OPENWORK_PORT:-${PORT:-8787}}"
WORKSPACE="${OPENWORK_WORKSPACE:-/data/workspace}"
DATA_DIR="${OPENWORK_DATA_DIR:-/data/openwork}"
SIDECAR_DIR="${OPENWORK_SIDECAR_DIR:-/data/sidecars}"
APPROVAL="${OPENWORK_APPROVAL_MODE:-manual}"
CORS="${OPENWORK_CORS_ORIGINS:-*}"
HOME_DIR="${HOME:-/data/home}"
PLUGIN_DIR="${OPENWORK_EXTENSIONS_PLUGIN_DIR:-/opt/openwork/opencode-plugins}"

mkdir -p "$WORKSPACE" "$DATA_DIR" "$SIDECAR_DIR" \
  "$HOME_DIR/.config" "$HOME_DIR/.local/share" "$HOME_DIR/.cache" "$HOME_DIR/.local/state"

for p in openwork-extensions-preview openwork-capabilities-knowledge openwork-office-attachments \
         openwork-anthropic-adaptive-thinking openwork-anthropic-tool-schema; do
  if [ ! -f "$PLUGIN_DIR/$p.js" ]; then
    echo "[worker] missing OpenCode plugin: $PLUGIN_DIR/$p.js" >&2
    exit 1
  fi
done

export OPENWORK_MANAGE_OPENCODE="${OPENWORK_MANAGE_OPENCODE:-1}"
export OPENWORK_OPENCODE_BIN="${OPENWORK_OPENCODE_BIN:-/usr/local/bin/opencode}"
export OPENWORK_EXTENSIONS_PLUGIN_DIR="$PLUGIN_DIR"
export OPENWORK_LOG_FORMAT="${OPENWORK_LOG_FORMAT:-json}"

echo "[worker] openwork-server $(openwork-server --version 2>/dev/null || echo unknown) / opencode $("$OPENWORK_OPENCODE_BIN" --version 2>/dev/null || echo unknown)"
echo "[worker] workspace=$WORKSPACE approval=$APPROVAL port=$PORT_TO_USE"

# Browser workbench. openwork-server serves the bundled web app from
# OPENWORK_WEB_ROOT and injects the client token into index.html. On a public
# URL that must sit behind a login, so when OPENWORK_WEB_PASSWORD is set the
# server binds to 127.0.0.1:8786 and web-gate.mjs fronts it on the public port.
# Without a password the web UI is disabled (OPENWORK_WEB_ROOT unset) and the
# worker behaves exactly as before (API + desktop/Den access only).
WEB_ROOT="${OPENWORK_WEB_ROOT:-}"
WEB_PASSWORD="${OPENWORK_WEB_PASSWORD:-}"
if [ -n "$WEB_ROOT" ] && [ ! -f "$WEB_ROOT/index.html" ]; then
  echo "[worker] OPENWORK_WEB_ROOT=$WEB_ROOT has no index.html; disabling web UI" >&2
  WEB_ROOT=""
fi

# --host 0.0.0.0 on purpose: openwork-server derives its internal engine URL
# from the bind host and treats 0.0.0.0 specially; '::' is not handled.
if [ -n "$WEB_ROOT" ] && [ -n "$WEB_PASSWORD" ]; then
  INTERNAL_PORT="${OPENWORK_INTERNAL_PORT:-8786}"
  echo "[worker] web UI enabled at / (password gate on :$PORT_TO_USE, server on 127.0.0.1:$INTERNAL_PORT)"
  export OPENWORK_WEB_ROOT="$WEB_ROOT"
  PORT="$PORT_TO_USE" OPENWORK_INTERNAL_PORT="$INTERNAL_PORT" node /opt/openwork/web-gate.mjs &
  GATE_PID=$!
  trap 'kill "$GATE_PID" 2>/dev/null' EXIT INT TERM
  exec openwork-server \
    --workspace "$WORKSPACE" \
    --host 0.0.0.0 \
    --port "$INTERNAL_PORT" \
    --cors "$CORS" \
    --approval "$APPROVAL" \
    "$@"
fi

if [ -n "$WEB_ROOT" ]; then
  echo "[worker] OPENWORK_WEB_PASSWORD is not set; web UI stays disabled on this public worker" >&2
fi
unset OPENWORK_WEB_ROOT
exec openwork-server \
  --workspace "$WORKSPACE" \
  --host 0.0.0.0 \
  --port "$PORT_TO_USE" \
  --cors "$CORS" \
  --approval "$APPROVAL" \
  "$@"
