#!/bin/sh
# Worker entrypoint: prepare the persistent volume, then run ipollowork-server
# (official iPolloWork agent host) with a managed OpenCode engine. Tokens are
# read from IPOLLOWORK_TOKEN / IPOLLOWORK_HOST_TOKEN (generated by the Railway
# template); if absent, the server generates them and logs the host token once.
#
# When IPOLLOWORK_WEB_PASSWORD is set, the official iPolloWork web UI is served
# on the public port behind a password login (web-gate.mjs) and the server binds
# to 127.0.0.1:$IPOLLOWORK_INTERNAL_PORT. Without a password the worker exposes
# only the API (desktop app / Den access) exactly as before.
set -eu

PORT_TO_USE="${PORT:-${IPOLLOWORK_PORT:-8787}}"
WORKSPACE="${IPOLLOWORK_WORKSPACE:-/data/workspace}"
DATA_DIR="${IPOLLOWORK_DATA_DIR:-/data/ipollowork}"
SIDECAR_DIR="${IPOLLOWORK_SIDECAR_DIR:-/data/sidecars}"
# auto = what the official desktop app uses for its own server; agent-level
# permission prompts (folders, shell, tools) are still enforced by the engine.
APPROVAL="${IPOLLOWORK_APPROVAL_MODE:-auto}"
CORS="${IPOLLOWORK_CORS_ORIGINS:-*}"
HOME_DIR="${HOME:-/data/home}"
# Template installs stage in $TMPDIR then rename() into $HOME/.config on the
# volume; keep both on the same filesystem or rename fails with EXDEV.
export TMPDIR="${TMPDIR:-/data/tmp}"
WEB_ROOT="${IPOLLOWORK_WEB_ROOT:-}"
WEB_PASSWORD="${IPOLLOWORK_WEB_PASSWORD:-}"

# Backwards compatibility with the earlier Openwork-based worker variables.
[ -n "${IPOLLOWORK_TOKEN:-}" ] || export IPOLLOWORK_TOKEN="${OPENWORK_TOKEN:-}"
[ -n "${IPOLLOWORK_HOST_TOKEN:-}" ] || export IPOLLOWORK_HOST_TOKEN="${OPENWORK_HOST_TOKEN:-}"
[ -n "$WEB_PASSWORD" ] || WEB_PASSWORD="${OPENWORK_WEB_PASSWORD:-}"

mkdir -p "$WORKSPACE" "$DATA_DIR" "$SIDECAR_DIR" "$TMPDIR" \
  "$HOME_DIR/.config" "$HOME_DIR/.local/share" "$HOME_DIR/.cache" "$HOME_DIR/.local/state"

export IPOLLOWORK_MANAGE_OPENCODE="${IPOLLOWORK_MANAGE_OPENCODE:-1}"
export IPOLLOWORK_OPENCODE_BIN="${IPOLLOWORK_OPENCODE_BIN:-/usr/local/bin/opencode}"
export IPOLLOWORK_LOG_FORMAT="${IPOLLOWORK_LOG_FORMAT:-json}"

echo "[worker] ipollowork-server $(ipollowork-server --version 2>/dev/null || echo unknown) / opencode $("$IPOLLOWORK_OPENCODE_BIN" --version 2>/dev/null || echo unknown)"
echo "[worker] workspace=$WORKSPACE approval=$APPROVAL port=$PORT_TO_USE"

# Projects added from the UI are persisted by the server in server.json, but a
# --workspace flag on the command line overrides that list on every start. Only
# seed the default project on first boot; afterwards let server.json rule.
SERVER_CONFIG="${IPOLLOWORK_SERVER_CONFIG:-$HOME_DIR/.config/ipollowork/server.json}"
export IPOLLOWORK_SERVER_CONFIG="$SERVER_CONFIG"
WORKSPACE_ARGS="--workspace $WORKSPACE"
if [ -f "$SERVER_CONFIG" ] && node -e '
  const c = JSON.parse(require("fs").readFileSync(process.argv[1], "utf8"));
  process.exit(Array.isArray(c.workspaces) && c.workspaces.length > 0 ? 0 : 1);
' "$SERVER_CONFIG" 2>/dev/null; then
  echo "[worker] using persisted project list from $SERVER_CONFIG"
  WORKSPACE_ARGS=""
fi

if [ -n "$WEB_ROOT" ] && [ ! -f "$WEB_ROOT/index.html" ]; then
  echo "[worker] IPOLLOWORK_WEB_ROOT=$WEB_ROOT has no index.html; web UI disabled" >&2
  WEB_ROOT=""
fi

# --host 0.0.0.0 on purpose: the server derives its internal engine URL from
# the bind host and treats 0.0.0.0 specially; '::' is not handled.
if [ -n "$WEB_ROOT" ] && [ -n "$WEB_PASSWORD" ]; then
  INTERNAL_PORT="${IPOLLOWORK_INTERNAL_PORT:-8786}"
  echo "[worker] official web UI enabled at / (login gate on :$PORT_TO_USE, server on 127.0.0.1:$INTERNAL_PORT)"
  PORT="$PORT_TO_USE" IPOLLOWORK_INTERNAL_PORT="$INTERNAL_PORT" IPOLLOWORK_WEB_PASSWORD="$WEB_PASSWORD" \
    IPOLLOWORK_WEB_ROOT="$WEB_ROOT" node /opt/ipollowork/web-gate.mjs &
  GATE_PID=$!
  trap 'kill "$GATE_PID" 2>/dev/null' EXIT INT TERM
  # shellcheck disable=SC2086
  exec ipollowork-server \
    $WORKSPACE_ARGS \
    --host 127.0.0.1 \
    --port "$INTERNAL_PORT" \
    --cors "$CORS" \
    --approval "$APPROVAL" \
    "$@"
fi

if [ -n "$WEB_ROOT" ]; then
  echo "[worker] IPOLLOWORK_WEB_PASSWORD is not set; the web UI stays disabled on this public worker" >&2
fi
# shellcheck disable=SC2086
exec ipollowork-server \
  $WORKSPACE_ARGS \
  --host 0.0.0.0 \
  --port "$PORT_TO_USE" \
  --cors "$CORS" \
  --approval "$APPROVAL" \
  "$@"
